# Permalinks
#
permalink:           pretty

# Setup
title:               Notes
tagline:             Links to remember
url:                 https://mpuig.github.io/
paginate:            10
baseurl:             /

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Marc Puig
