# Permalinks
#
permalink:           pretty

# Setup
title:               Notes
tagline:             Links to remember
url:                 https://mpuig.github.io/
paginate:            10
baseurl:             /

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Marc Puig
  twitter:           mpuig
  url:               https://twitter.com/mpuig
  email:             marc.puig+notes@gmail.com


# Custom vars
version:             0.1.0
github:
  repo:              https://github.com/mpuig.github.io

gems:
  - jekyll-paginate
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: Marc
      twitter: mpuig
